import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The sitemap must only advertise URLs that resolve.
 *
 * A sitemap entry pointing at a redirect is worse than a missing one: it tells a
 * crawler a URL is worth indexing and then hands it something else. `/app/search`
 * was the live example — it 307-redirects to `/app/search?q=` because the route
 * validates its search params, so it is now excluded.
 *
 * The guard below reads the generated file and checks each entry against the
 * route directory, so a newly added route cannot silently land in the sitemap
 * while redirecting.
 */

const read = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

/** Routes that redirect, are private, or are not content. */
const EXCLUDED = new Set([
  "/cbt", // noindex, timed attempt with private in-progress state
  "/app/search", // 307-redirects to /app/search?q=
]);

function sitemapPaths(): string[] {
  const xml = read("public/sitemap.xml");
  // Strip the origin first, then take the path. Matching lazily inside the URL
  // would capture a fragment of the host instead of the path.
  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1] ?? "")
    .map((url) => url.replace(/^https?:\/\/[^/]+/, "") || "/");
  expect(locs.length).toBeGreaterThan(0);
  return locs;
}

describe("the sitemap only lists URLs that resolve", () => {
  it("does not list a redirecting or private route", () => {
    for (const p of sitemapPaths()) {
      expect(EXCLUDED.has(p), `${p} must not be advertised`).toBe(false);
    }
  });

  it("lists the landing page and every content route", () => {
    const paths = sitemapPaths();
    for (const expected of [
      "/",
      "/app",
      "/app/pyq",
      "/app/map",
      "/app/studytube",
      "/app/tests",
      "/privacy",
      "/terms",
      "/about",
    ]) {
      expect(paths, expected).toContain(expected);
    }
  });

  it("has no duplicate URLs", () => {
    const paths = sitemapPaths();
    expect(new Set(paths).size).toBe(paths.length);
  });

  it("gives every entry a lastmod, changefreq and priority", () => {
    const xml = read("public/sitemap.xml");
    const urls = xml.split("<url>").slice(1);
    expect(urls.length).toBeGreaterThan(0);
    for (const u of urls) {
      expect(u).toMatch(/<loc>/);
      expect(u).toMatch(/<lastmod>\d{4}-\d{2}-\d{2}<\/lastmod>/);
      expect(u).toMatch(/<changefreq>/);
      expect(u).toMatch(/<priority>/);
    }
  });

  it("excludes the search interface from robots as well", () => {
    // Belt and braces: a search page with an empty query is thin content, and
    // it is also the route most likely to be crawled into useless URLs.
    const robots = read("public/robots.txt");
    expect(robots).toMatch(/Disallow: \/app\/search/);
  });

  it("is regenerated by the build, so it cannot drift from the routes", () => {
    const script = read("scripts/build-sitemap.mjs");
    expect(script).toContain("readdirSync");
    const pkg = JSON.parse(read("package.json")) as { scripts: Record<string, string> };
    const build = pkg.scripts["build"] ?? "";
    expect(build).toContain("build-sitemap");
    // And it must run *before* vite copies public/ into the output, or the
    // sitemap is generated and then never shipped.
    expect(build.indexOf("build-sitemap")).toBeLessThan(build.indexOf("vite build"));
  });
});

/**
 * A route that shows one student's own data must not be indexable.
 *
 * Leaving a URL out of the sitemap only stops it being *submitted* for
 * crawling. If it is ever linked, shared or bookmarked it can still be indexed,
 * and an indexed attempt page is a student's result sitting in a search engine
 * for anyone to find. `/cbt` already carried the meta; the attempt-detail route
 * did not, so an individual result was the one private page without it.
 */
describe("private routes are not indexable", () => {
  it("marks the attempt-detail route noindex", () => {
    const route = read("src/routes/app.attempts.$attemptId.tsx");
    expect(route).toMatch(/name:\s*"robots",\s*content:\s*"noindex,\s*nofollow"/);
  });

  it("still marks the in-progress exam noindex", () => {
    const route = read("src/routes/cbt.tsx");
    expect(route).toMatch(/name:\s*"robots",\s*content:\s*"noindex,\s*nofollow"/);
  });

  it("keeps neither in the sitemap", () => {
    const paths = sitemapPaths();
    for (const p of paths) {
      expect(p.startsWith("/app/attempts/"), `${p} is private`).toBe(false);
      expect(p, `${p} is private`).not.toBe("/cbt");
    }
  });
});
