import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The sitemap must only advertise URLs that resolve.
 *
 * A sitemap entry pointing at a redirect is worse than a missing one: it tells a
 * crawler a URL is worth indexing and then hands it something else. `/app/search`
 * was the live example — it 307-redirects to `/app/search?q=` because the route
 * validates its search params, so it is now excluded.
 *
 * The guard below reads the generated file and checks each entry against the
 * route directory, so a newly added route cannot silently land in the sitemap
 * while redirecting.
 */

const read = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

/** Routes that redirect, are private, or are not content. */
const EXCLUDED = new Set([
  "/cbt", // noindex, timed attempt with private in-progress state
  "/app/search", // 307-redirects to /app/search?q=
]);

function sitemapPaths(): string[] {
  const xml = read("public/sitemap.xml");
  // Strip the origin first, then take the path. Matching lazily inside the URL
  // would capture a fragment of the host instead of the path.
  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1] ?? "")
    .map((url) => url.replace(/^https?:\/\/[^/]+/, "") || "/");
  expect(locs.length).toBeGreaterThan(0);
  return locs;
}

describe("the sitemap only lists URLs that resolve", () => {
  it("does not list a redirecting or private route", () => {
    for (const p of sitemapPaths()) {
      expect(EXCLUDED.has(p), `${p} must not be advertised`).toBe(false);
    }
  });

  it("lists the landing page and every content route", () => {
    const paths = sitemapPaths();
    for (const expected of [
      "/",
      "/app",
      "/app/pyq",
      "/app/map",
      "/app/studytube",
      "/app/tests",
      "/privacy",
      "/terms",
      "/about",
    ]) {
      expect(paths, expected).toContain(expected);
    }
  });

  it("has no duplicate URLs", () => {
    const paths = sitemapPaths();
    expect(new Set(paths).size).toBe(paths.length);
  });

  it("gives every entry a lastmod, changefreq and priority", () => {
    const xml = read("public/sitemap.xml");
    const urls = xml.split("<url>").slice(1);
    expect(urls.length).toBeGreaterThan(0);
    for (const u of urls) {
      expect(u).toMatch(/<loc>/);
      expect(u).toMatch(/<lastmod>\d{4}-\d{2}-\d{2}<\/lastmod>/);
      expect(u).toMatch(/<changefreq>/);
      expect(u).toMatch(/<priority>/);
    }
  });

  it("excludes the search interface from robots as well", () => {
    // Belt and braces: a search page with an empty query is thin content, and
    // it is also the route most likely to be crawled into useless URLs.
    const robots = read("public/robots.txt");
    expect(robots).toMatch(/Disallow: \/app\/search/);
  });

  it("is regenerated by the build, so it cannot drift from the routes", () => {
    const script = read("scripts/build-sitemap.mjs");
    expect(script).toContain("readdirSync");
    const pkg = JSON.parse(read("package.json")) as { scripts: Record<string, string> };
    const build = pkg.scripts["build"] ?? "";
    expect(build).toContain("build-sitemap");
    // And it must run *before* vite copies public/ into the output, or the
    // sitemap is generated and then never shipped.
    expect(build.indexOf("build-sitemap")).toBeLessThan(build.indexOf("vite build"));
  });
});

describe("the landing page is real content, not a redirect", () => {
  const html = read("public/index.html");

  it("no longer meta-refreshes to the legacy shell", () => {
    // `/` used to be a 515-byte meta-refresh to `jee-cbt.html`, so the site's
    // strongest URL sent every visitor — and every crawler — somewhere else.
    expect(html).not.toContain('http-equiv="refresh"');
  });

  it("links into the app rather than bouncing away", () => {
    expect(html).toContain('href="/app"');
  });

  it("carries its own metadata and a canonical", () => {
    expect(html).toContain("<title>");
    expect(html).toContain('rel="canonical"');
    expect(html).toContain('property="og:image"');
  });

  it("keeps the legacy platform reachable for anyone who bookmarked it", () => {
    // The legacy shell is not deleted, only demoted from the site root.
    expect(html).toContain('href="/jee-cbt.html"');
  });

  it("links the legal pages from the landing page too", () => {
    for (const p of ["/privacy", "/terms", "/about"]) {
      expect(html, p).toContain(`href="${p}"`);
    }
  });
});
