/**
 * Typed access to the snapshot of the legacy inline academic data.
 *
 * Snapshot is generated by scripts/extract-legacy-data.mjs from the real
 * literals in public/jee-cbt.html. Do not hand-edit this file; re-run the
 * extractor if the legacy data changes.
 */

import raw from "./legacy-inline.json";

type TopicTuple = [name: string, weightJee: number, weightBoard: number, classLevel: number];
type ExtraTopicTuple = [name: string, weightJee: number, weightBoard: number];
type DepthKey = "crash" | "focused" | "standard" | "mastery";
type Target = "jeemain" | "jeeadv" | "board12" | "board11" | "cbse27";

export interface LegacyTopicPlan {
  Physics: TopicTuple[];
  Chemistry: TopicTuple[];
  Mathematics: TopicTuple[];
}

export interface LegacyBoardExtra {
  English: ExtraTopicTuple[];
}

export interface LegacyTeacher {
  id: string;
  name: string;
  instituteId: string;
  subject: "Physics" | "Chemistry" | "Mathematics";
  specialization?: string;
  examTarget: Target[];
  batchInfo?: string;
  channelName: string;
}

export interface LegacyChannelMap {
  Physics: string[];
  Chemistry: string[];
  Mathematics: string[];
}

export interface LegacyDepthPlan {
  label: string;
  icon: string;
  color: string;
  kind: "oneshot" | "lecture" | "detailed";
  est: [number, number, number, number];
  pr: [number, number, number, number];
  prMin: number;
  adv: boolean;
  rev: Array<[number, number]>;
  hi: string;
}

export type LegacyDepthMap = Record<DepthKey, LegacyDepthPlan>;

export interface LegacyInlineSnapshot {
  schema: number;
  extractedAt: string;
  sourceFile: string;
  data: {
    jeeTopics: LegacyTopicPlan;
    boardExtraTopics: LegacyBoardExtra;
    advExtraTopics: Record<"Physics" | "Chemistry" | "Mathematics", ExtraTopicTuple[]>;
    cbse27Topics: Record<"Physics" | "Chemistry" | "Mathematics", ExtraTopicTuple[]>;
    aipDepths: LegacyDepthMap;
    aipTeachers: LegacyTeacher[];
    aipChannels: LegacyChannelMap;
  };
}

export const LEGACY_INLINE = raw as LegacyInlineSnapshot;

export function getLegacyTopics() {
  return LEGACY_INLINE.data.jeeTopics;
}

export function getLegacyTeachers() {
  return LEGACY_INLINE.data.aipTeachers;
}
