#!/usr/bin/env node
/**
 * VALIDATE FULL PLATFORM — every pure-logic feature, on a LARGE generated dataset.
 *
 * Bundles the REAL source modules with Rolldown and runs the actual functions
 * against big synthetic corpora so every decision path in the app is exercised:
 *
 *  - CBT scoring engine    (evaluate / isRight / ntaPercentile)
 *  - Post-test analytics   (analyseQuestions / topicBreakdown / mistakeDoctor / inferTag)
 *  - Readiness + weak-topic (computeReadiness) over a large attempt history
 *  - AI Planner engine     (planRecommendations / rank / buildQueries ...)
 *  - PYQ pipeline          (parseIntegerKey / transformRow / parsePaperId / buildDataset)
 *  - Focus system          (todayFocusSeconds / focusStreak / localKey / fmtFocus)
 *  - StudyTube catalog     (offlineCatalog / dreamChannels)
 *  - Persistence bridge    (DataStore / localDayKey)
 *
 * No network. Deterministic RNG (seeded LCG) so results are reproducible.
 * Exits non-zero on any failed assertion (CI-friendly).
 */

import { build } from "rolldown";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src");

/* ------------------------------------------------------------------ */
/* Tiny test framework                                                */
/* ------------------------------------------------------------------ */
let passed = 0;
let failed = 0;
const failures = [];
const stats = { cases: 0, throws: 0 };

function ok(cond, label) {
  stats.cases++;
  if (cond) passed++;
  else {
    failed++;
    failures.push(label);
    console.error("  ✗ " + label);
  }
}
function section(title) {
  console.log("\n=== " + title + " ===");
}

/* ------------------------------------------------------------------ */
/* Seeded deterministic RNG (LCG)                                     */
/* ------------------------------------------------------------------ */
function makeRng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 2 ** 32;
  };
}

/* ------------------------------------------------------------------ */
/* Build the bundle with all feature modules                          */
/* ------------------------------------------------------------------ */
let P;
async function buildBundle() {
  const dir = await mkdtemp(join(tmpdir(), "ntacbt-full-"));
  const entryPath = join(dir, "entry.ts");
  const out = join(dir, "bundle.mjs");
  const lines = [
    "// @generated by scripts/validate-full.mjs",
    `export * as cbtEngine from ${JSON.stringify(join(SRC, "features", "cbt", "engine"))};`,
    `export * as cbtAnalytics from ${JSON.stringify(join(SRC, "features", "cbt", "analytics"))};`,
    `export * as cbtTypes from ${JSON.stringify(join(SRC, "features", "cbt", "types"))};`,
    `export * as readiness from ${JSON.stringify(join(SRC, "features", "readiness", "readiness"))};`,
    `export * as store from ${JSON.stringify(join(SRC, "lib", "store"))};`,
    `export * as plannerEngine from ${JSON.stringify(join(SRC, "features", "planner", "engine"))};`,
    `export * as plannerNormalize from ${JSON.stringify(join(SRC, "features", "planner", "normalize"))};`,
    `export * as plannerAdapt from ${JSON.stringify(join(SRC, "features", "planner", "adapt"))};`,
    `export * as catalog from ${JSON.stringify(join(SRC, "features", "studytube", "catalog"))};`,
    `export * as focus from ${JSON.stringify(join(SRC, "features", "focus", "focus"))};`,
    `export * as pyq from ${JSON.stringify(join(SRC, "routes", "api", "public", "pyq-papers"))};`,
    `export * as video from ${JSON.stringify(join(SRC, "data", "video-engine"))};`,
    `export * as syllabus from ${JSON.stringify(join(SRC, "data", "syllabus"))};`,
  ];
  await writeFile(entryPath, lines.join("\n"), "utf8");
  const res = await build({
    input: entryPath,
    output: { file: out, format: "esm", codeSplitting: false },
    resolve: { tsconfigFilename: join(ROOT, "tsconfig.json") },
    platform: "node",
  });
  if (!res || !res.output) throw new Error("Rolldown produced no output");
  P = await import(pathToFileURL(out).href);
  return dir;
}

function hashStr(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (Math.imul(31, h) + s.charCodeAt(i)) | 0;
  return h;
}

/* ------------------------------------------------------------------ */
/* Dataset generators                                                 */
/* ------------------------------------------------------------------ */
const SUBJECTS = ["Physics", "Chemistry", "Mathematics"];
const TYPES = ["mcq", "integer"];
const TAGS = ["concept", "formula", "calculation", "misread", "silly", "guessed"];

function genQuestion(rng, i) {
  const subj = SUBJECTS[Math.floor(rng() * 3)];
  const type = rng() < 0.7 ? "mcq" : "integer";
  const q = {
    id: `q${i}`,
    no: i + 1,
    subject: subj,
    chapter: `Chapter ${Math.floor(rng() * 8) + 1}`,
    topic: `Topic ${Math.floor(rng() * 4) + 1}`,
    type,
    text: `Question ${i + 1} about physics/maths`,
    options: [],
    answer:
      type === "mcq"
        ? ["a", "b", "c", "d"][Math.floor(rng() * 4)]
        : String(Math.floor(rng() * 101)),
  };
  if (type === "mcq") {
    q.options = ["a", "b", "c", "d"].map((label) => ({ label, text: `Opt ${label}` }));
  } else if (rng() < 0.2) {
    q.accept = { kind: "range", lo: 40, hi: 60 };
    q.answer = "50";
  }
  if (rng() < 0.3) q.tag = TAGS[Math.floor(rng() * TAGS.length)];
  if (rng() < 0.5) q.sol = "Solution explanation here";
  return q;
}

function genTest(rng, n) {
  const questions = Array.from({ length: n }, (_, i) => genQuestion(rng, i));
  return {
    id: `test-${Math.floor(rng() * 1e6)}`,
    name: "Generated Test",
    createdAt: Date.now(),
    durationSec: 180 * 60,
    questions,
  };
}

function genResponses(rng, test, skipRate) {
  const responses = {};
  for (const q of test.questions) {
    const r = rng();
    if (r < skipRate) {
      responses[q.id] = { ans: null, time: Math.floor(rng() * 300) };
    } else {
      // mix correct / wrong
      const correct = rng() < 0.55;
      responses[q.id] = {
        ans: correct
          ? q.answer
          : q.type === "mcq"
            ? ["a", "b", "c", "d"].filter((x) => x !== q.answer)[Math.floor(rng() * 3)]
            : String(Number(q.answer) + 7),
        time: Math.floor(rng() * 400),
      };
    }
  }
  return responses;
}

function genPyqRows(rng, count) {
  const rows = [];
  const papers = [
    "jee-main-2024-online-27th-january-morning-shift",
    "jee-main-2025-online-22nd-january-evening-shift",
    "aieee-2013",
  ];
  for (let i = 0; i < count; i++) {
    const paperId = papers[Math.floor(rng() * papers.length)];
    const mcq = rng() < 0.7;
    rows.push({
      paper_id: paperId,
      subject: ["physics", "chemistry", "maths"][Math.floor(rng() * 3)],
      question: `PYQ question ${i} text with math`,
      question_type: mcq ? "mcq" : "integer",
      options: JSON.stringify(
        ["a", "b", "c", "d"].map((label) => ({ identifier: label, content: `Opt ${label}` })),
      ),
      correct_option: JSON.stringify(["a", "b", "c", "d"][Math.floor(rng() * 4)]),
      answer: mcq ? "" : Math.floor(rng() * 100).toString(),
      explanation: `Solution for ${i}`,
      chapter: `Chapter ${Math.floor(rng() * 10) + 1}`,
      topic: `Topic ${Math.floor(rng() * 5) + 1}`,
    });
  }
  return rows;
}

async function main() {
  section("Build full-stack bundle");
  const dir = await buildBundle();
  ok(typeof P.cbtEngine.evaluate === "function", "cbtEngine.evaluate exported");
  ok(typeof P.cbtAnalytics.analyseQuestions === "function", "cbtAnalytics exported");
  ok(typeof P.readiness.computeReadiness === "function", "readiness exported");
  ok(typeof P.plannerEngine.planRecommendations === "function", "planner exported");
  ok(typeof P.pyq.buildDataset === "function", "pyq exported");
  ok(typeof P.focus.focusStreak === "function", "focus exported");
  ok(typeof P.catalog.offlineCatalog === "function", "catalog exported");
  console.log("  bundle loaded");

  const rng = makeRng(20240001);
  const { isRight, evaluate, ntaPercentile } = P.cbtEngine;
  const { analyseQuestions, topicBreakdown, mistakeDoctor, inferTag, classLabel } = P.cbtAnalytics;
  const { computeReadiness } = P.readiness;
  const { DataStore, localDayKey } = P.store;
  const { sanitizePlannerRequest, hasPlannerTopic } = P.plannerNormalize;
  const {
    planRecommendations,
    rank,
    buildQueries,
    mergeRecommendations,
    parseDuration,
    parseSearchPage,
  } = P.plannerEngine;
  const { adaptTasks } = P.plannerAdapt;
  const { offlineCatalog, dreamChannels } = P.catalog;
  const { localKey, todayFocusSeconds, focusStreak, fmtFocus } = P.focus;
  const { parseIntegerKey, transformRow, parsePaperId, buildDataset } = P.pyq;

  /* ------------------------------------------------------------------ */
  section("CBT scoring over a large set of generated tests");
  for (let t = 0; t < 120; t++) {
    const test = genTest(rng, 75);
    const responses = genResponses(rng, test, 0.2);
    const res = evaluate(test, responses, true);
    ok(res.all.total === 75, `test ${t}: total 75`);
    ok(
      res.all.correct + res.all.wrong + res.all.skipped === 75,
      `test ${t}: correct+wrong+skipped === total`,
    );
    ok(res.all.accuracy >= 0 && res.all.accuracy <= 100, `test ${t}: accuracy in range`);
    ok(res.all.max === 300, `test ${t}: max = 300`);
    ok(res.all.marks >= -75 && res.all.marks <= 300, `test ${t}: marks bounded`);
    // subject sums must add to all
    const subjCorrect = SUBJECTS.reduce((n, s) => n + (res.per[s]?.correct || 0), 0);
    ok(subjCorrect === res.all.correct, `test ${t}: subject correct sums match`);
    // percentage
    ok(res.all.percentage >= -25 && res.all.percentage <= 100, `test ${t}: percentage sane`);
    // isRight matches evaluate's right count
    let rightCount = 0;
    for (const q of test.questions) {
      const a = responses[q.id]?.ans ?? null;
      if (a != null && a !== "" && isRight(q, a)) rightCount++;
    }
    ok(rightCount === res.all.correct, `test ${t}: isRight count matches`);
  }

  /* ------------------------------------------------------------------ */
  section("NTA percentile anchors (real boundaries + monotonicity)");
  ok(ntaPercentile(25) === 47.4, "25 marks -> 47.4 (dense anchor present)");
  ok(ntaPercentile(45) === 77.2, "45 marks -> 77.2 (dense anchor present)");
  ok(ntaPercentile(165) === 99.15, "165 marks -> 99.15 (dense anchor present)");
  ok(ntaPercentile(0) === 0.84, "0 marks -> 0.84");
  ok(ntaPercentile(160) === 99.03, "160 marks -> 99.03");
  ok(ntaPercentile(300) >= 99.9, "300 marks -> near-max percentile (caps at 100 as a %)");
  ok(ntaPercentile(-50) === 0.84, "negative clamps to min");
  ok(ntaPercentile(999) > 99.9, "over 300 clamps high");
  let prev = -1;
  for (let m = 0; m <= 300; m += 1) {
    const p = ntaPercentile(m);
    ok(p >= prev, `percentile monotonic at ${m}`);
    prev = p;
  }
  // Cross-surface consistency: the React engine must agree with the legacy
  // dense table exactly (same marks -> same percentile) at every integer mark.
  // This catches a sparse-vs-dense table drift that would show different
  // percentiles depending on which page the student views.
  const LEGACY_TABLE = [
    [0, 0.84],
    [5, 4.5],
    [10, 9.7],
    [15, 20.6],
    [20, 37.69],
    [25, 47.4],
    [30, 56.57],
    [35, 64.2],
    [40, 71.3],
    [45, 77.2],
    [50, 80.98],
    [55, 84.6],
    [60, 86.91],
    [65, 88.8],
    [70, 90.41],
    [75, 91.7],
    [80, 93.0],
    [85, 94.1],
    [90, 95.0],
    [95, 95.8],
    [100, 96.0],
    [110, 96.9],
    [120, 97.5],
    [130, 98.32],
    [140, 98.67],
    [150, 98.99],
    [160, 99.03],
    [165, 99.15],
    [170, 99.27],
    [180, 99.46],
    [190, 99.6],
    [200, 99.71],
    [210, 99.795],
    [220, 99.852],
    [230, 99.901],
    [240, 99.935],
    [250, 99.95],
    [260, 99.977],
    [270, 99.99],
    [280, 99.994],
    [290, 99.9991],
    [300, 99.99999],
  ];
  const legacyPct = (m) => {
    const mm = Math.min(300, Math.max(0, m));
    for (let i = 1; i < LEGACY_TABLE.length; i++) {
      if (mm <= LEGACY_TABLE[i][0]) {
        const [m0, p0] = LEGACY_TABLE[i - 1];
        const [m1, p1] = LEGACY_TABLE[i];
        const p = p0 + (p1 - p0) * ((mm - m0) / (m1 - m0 || 1));
        return +p.toFixed(mm >= 240 ? 4 : 2);
      }
    }
    return 99.99999;
  };
  // Tolerance 0.015 absorbs a sub-0.01 float rounding-mode difference at exact
  // half-cent boundaries (legacy uses toFixed; the React engine uses round).
  // A sparse-vs-dense drift would show up as a ~0.1..1.0 point delta >> 0.015.
  for (let m = 0; m <= 300; m += 5) {
    ok(Math.abs(ntaPercentile(m) - legacyPct(m)) < 0.015, `percentile matches legacy at ${m}`);
  }

  /* ------------------------------------------------------------------ */
  section("Post-test analytics over generated attempts");
  const test = genTest(rng, 75);
  const responses = genResponses(rng, test, 0.15);
  const res = evaluate(test, responses, true);
  const insights = analyseQuestions(test, res, responses);
  ok(insights.length === 75, "analyseQuestions returns one insight per question");
  ok(
    insights.every((i) => i.questionId && i.subject && i.className),
    "insights well-formed",
  );
  const breakdown = topicBreakdown(test, insights);
  ok(Array.isArray(breakdown), "topicBreakdown array");
  ok(
    breakdown.every((b) => b.total > 0 && b.accuracy >= 0 && b.accuracy <= 100),
    "topicBreakdown sane",
  );
  const doc = mistakeDoctor(
    insights,
    test.questions.map((q) => ({ q })),
  );
  ok(doc && Array.isArray(doc.topClasses), "mistakeDoctor returns topClasses");
  ok(
    doc.pattern === null || (doc.pattern.count >= 1 && typeof doc.pattern.fix === "string"),
    "mistakeDoctor pattern sane",
  );
  ok(
    ["fast-correct", "slow-correct", "fast-wrong", "slow-wrong", "wasted", "lucky"].includes(
      insights[0].className,
    ),
    "classLabel maps known classes",
  );
  ok(classLabel(insights[0].className).length > 0, "classLabel returns label");
  // inferTag deterministic
  const taggedQ = { ...test.questions[0], text: "Calculate the value of x", sol: "formula" };
  ok(
    typeof inferTag(taggedQ) === "string" || inferTag(taggedQ) === null,
    "inferTag returns string or null",
  );

  /* ------------------------------------------------------------------ */
  section("Readiness over a large attempt history (weak-topic detection)");
  // Build a store with ~8 tests and many attempts, some topics badly weak.
  const now = Date.now();
  const attempts = [];
  const tests = [];
  for (let t = 0; t < 8; t++) {
    const tt = genTest(rng, 75);
    tests.push({
      ...tt,
      id: `t${t}`,
      createdAt: now - (8 - t) * 86400000,
      questions: tt.questions.map((q) => ({
        ...q,
        chapter: `Ch${Math.floor(rng() * 4) + 1}`,
        subject: SUBJECTS[Math.floor(rng() * 3)],
      })),
    });
    const resp = genResponses(rng, tt, 0.3);
    const a = {
      id: `a${t}`,
      testId: `t${t}`,
      submittedAt: now - (8 - t) * 86400000,
      responses: {},
    };
    for (const q of tt.questions) {
      const r = resp[q.id];
      a.responses[q.id] = {
        ans: r?.ans ?? null,
        status: r?.ans ? "answered" : "notanswered",
        time: r?.time || 0,
        changes: 0,
      };
    }
    const ev = evaluate(tt, resp, true);
    a.result = {
      all: {
        correct: ev.all.correct,
        wrong: ev.all.wrong,
        skipped: ev.all.skipped,
        marks: ev.all.marks,
        neg: ev.all.neg,
        time: ev.all.time,
        total: ev.all.total,
        max: ev.all.max,
        accuracy: ev.all.accuracy,
      },
    };
    attempts.push(a);
  }
  const store = new DataStore({
    attempts,
    tests,
    settings: {},
    dailyQuestions: {},
    reviewSchedule: {},
    qtags: {},
    aiPlanner: {
      profile: {
        target: "jeemain",
        language: "en",
        depth: "lecture",
        speed: 1,
        dailyMin: 120,
        weekdayMin: 90,
        startDate: localDayKey(now),
        days: 60,
      },
      tasks: tests.flatMap((tt, i) =>
        tt.questions.slice(0, 2).map((q, j) => ({
          id: `task-${i}-${j}`,
          subject: q.subject,
          chapter: q.chapter,
          topic: q.topic || "",
          kind: "learn",
          date: localDayKey(now + (i % 3) * 86400000),
          estMin: 45,
          status: i % 2 === 0 ? "done" : "pending",
        })),
      ),
    },
    plannerDone: { "task-0-0": true },
    plannerEdits: {},
  });
  const rs = computeReadiness(store);
  ok(
    typeof rs.accuracy === "number" && rs.accuracy >= 0 && rs.accuracy <= 100,
    "readiness accuracy in range",
  );
  ok(Array.isArray(rs.weakTopics), "readiness weakTopics array");
  ok(
    rs.weakTopics.every((w) => w.subject && w.chapter && typeof w.accuracy === "number"),
    "weak topics well-formed",
  );
  ok(
    typeof rs.syllabusCompletionPct === "number" &&
      rs.syllabusCompletionPct >= 0 &&
      rs.syllabusCompletionPct <= 100,
    "syllabus completion in range",
  );
  ok(Array.isArray(rs.messages.next) && rs.messages.next.length >= 1, "readiness messages present");
  ok(rs.today && typeof rs.today.plannedMinutes === "number", "readiness today plan present");
  // plannerDone overlay
  ok(
    store.planner.tasks.find((t) => t.id === "task-0-0")?.status === "done",
    "plannerDone overlays done status",
  );

  /* ------------------------------------------------------------------ */
  section("AI Planner on many topics (real curated + fallback)");
  const stubSearch = async (q) => [
    {
      id: "v" + hashStr(q).toString(36),
      title: `${q.split(" ")[0]} Full Lecture JEE Main | Physics Wallah`,
      channel: "JEE Wallah",
      channelId: "UCx",
      durationSec: 7200,
      published: "1y",
      live: false,
    },
    {
      id: "v2" + hashStr(q).toString(36),
      title: `One Shot Revision`,
      channel: "Unacademy",
      channelId: "UCy",
      durationSec: 3600,
      published: "1m",
      live: false,
    },
  ];
  const topics = [
    "Units and Measurements",
    "Kinematics",
    "Laws of Motion",
    "Rotational Motion",
    "Electrostatics",
    "Current Electricity",
    "Magnetism",
    "Optics",
    "Thermodynamics",
    "Chemical Bonding",
    "Mole Concept",
    "Organic Chemistry",
    "Algebra",
    "Calculus",
    "Statistics & Probability",
  ];
  const targets = ["jeemain", "jeeadv", "board12", "board11", "cbse27"];
  const kinds = ["learn", "practice", "revision", "advanced"];
  const depths = ["oneshot", "lecture", "detailed"];
  const langs = ["en", "hi", "hinglish"];
  for (const topic of topics) {
    for (const kind of kinds) {
      for (const target of targets) {
        for (const lang of langs) {
          const req = sanitizePlannerRequest({
            topic,
            subject: "Physics",
            kind,
            depth: "lecture",
            target,
            language: lang,
          });
          const out = await planRecommendations(req, stubSearch);
          ok(
            Array.isArray(out.items) && out.items.length <= 6,
            `plan ok: ${topic}/${kind}/${target}/${lang}`,
          );
          ok(typeof out.fallback === "boolean", "fallback boolean");
        }
      }
    }
  }
  // adversarial request robustness
  for (const bad of [
    null,
    undefined,
    42,
    "x",
    [],
    { topic: { evil: 1 } },
    { maxMinutes: "NaN" },
    { kind: "nonsense" },
  ]) {
    const req = sanitizePlannerRequest(bad);
    ok(
      hasPlannerTopic(req) === (typeof req.topic === "string" && req.topic.length > 0),
      `sanitize never throws (${JSON.stringify(bad)?.slice(0, 20)})`,
    );
  }

  /* ------------------------------------------------------------------ */
  section("PYQ pipeline over a large generated row set");
  const rows = genPyqRows(rng, 5000);
  const ds = buildDataset(rows);
  ok(ds.index.length > 0, "buildDataset produces papers");
  ok(Object.keys(ds.papers).length === ds.index.length, "papers match index");
  for (const meta of ds.index) {
    const qs = ds.papers[meta.id];
    ok(qs && qs.length >= 30, `paper ${meta.id} has >=30 questions`);
    ok(
      qs.every((q) => q.no >= 1 && q.subject && q.type && q.answer !== undefined),
      `paper ${meta.id} questions well-formed`,
    );
    ok(qs.length === meta.total, `paper ${meta.id} total matches`);
    // NTA on-screen order: MCQ before integer within subject groups, subjects in order
    ok(
      SUBJECTS.every((s) =>
        qs
          .filter((q) => q.subject === s)
          .every((q, i, arr) => {
            const idx = arr.findIndex((x) => x.type === "mcq");
            return idx === -1 ? true : i >= idx;
          }),
      ),
      `paper ${meta.id} MCQ-before-integer per subject`,
    );
  }
  // parseIntegerKey edge cases
  ok(parseIntegerKey("600to700").accept?.kind === "range", "range key parsed");
  ok(parseIntegerKey("30OR60").accept?.kind === "any", "any key parsed");
  ok(parseIntegerKey("Bonus").accept?.kind === "all", "bonus -> all");
  ok(parseIntegerKey("58").answer === "58", "plain key");
  // transformRow rejects malformed rows
  ok(transformRow({}) === null, "empty row rejected");
  ok(
    transformRow({
      paper_id: "x",
      subject: "physics",
      question: "q",
      question_type: "mcq",
      options: "not json",
      correct_option: "[]",
    }) === null,
    "bad options rejected",
  );
  // parsePaperId
  ok(parsePaperId("aieee-2013")?.month === "AIEEE", "aieee id parsed");

  /* ------------------------------------------------------------------ */
  section("Focus system across a large session history");
  const sessions = [];
  for (let d = 0; d < 40; d++) {
    const day = now - d * 86400000;
    const n = Math.floor(rng() * 4);
    for (let i = 0; i < n; i++) {
      sessions.push({
        id: `s${d}-${i}`,
        startedAt: day - i * 60000,
        seconds: Math.floor(rng() * 3600),
        completed: rng() < 0.8,
        label: "Focus",
        subject: "Physics",
      });
    }
  }
  ok(todayFocusSeconds(sessions, now) >= 0, "todayFocusSeconds non-negative");
  ok(focusStreak(sessions, now) >= 0, "focusStreak non-negative");
  ok(localKey(now) === localDayKey(now), "focus localKey matches store day key");
  ok(fmtFocus(90) === "01:30", "fmtFocus formats");
  ok(fmtFocus(0) === "00:00", "fmtFocus zero");
  // consecutive-day streak correctness
  const s3 = [
    { id: "a", startedAt: now, seconds: 1800, completed: true, label: "x" },
    { id: "b", startedAt: now - 86400000, seconds: 1800, completed: true, label: "x" },
    { id: "c", startedAt: now - 2 * 86400000, seconds: 1800, completed: true, label: "x" },
  ];
  ok(focusStreak(s3, now) === 3, "focusStreak counts 3 consecutive days");

  /* ------------------------------------------------------------------ */
  section("StudyTube offline catalog (always-works fallback)");
  for (const subject of ["Physics", "Chemistry", "Mathematics", "English", ""]) {
    const items = offlineCatalog({
      topic: "Kinematics",
      subject,
      language: "hinglish",
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    ok(items.length >= 1, `offlineCatalog non-empty for ${subject}`);
    ok(
      items.every((i) => i.externalUrl?.startsWith("https://")),
      `offlineCatalog externalUrl https (${subject})`,
    );
  }

  /* ------------------------------------------------------------------ */
  section("Merge / rank invariants on live candidates");
  const live = [
    {
      id: "r1",
      title: "Kinematics Projectile one shot JEE Main",
      channel: "Physics Wallah",
      channelId: "u2",
      durationSec: 7200,
      published: "2y",
      live: false,
    },
    {
      id: "r2",
      title: "#shorts song",
      channel: "Music",
      channelId: "u3",
      durationSec: 20,
      published: "1y",
      live: false,
    },
    {
      id: "r3",
      title: "LIVE",
      channel: "Live",
      channelId: "u4",
      durationSec: 0,
      published: "",
      live: true,
    },
  ];
  const ranked = rank(live, "Kinematics", "en", "learn", 180);
  ok(
    ranked.every((i) => i.durationSec >= 65 && !/#shorts|song/i.test(i.title)),
    "rank filters shorts/live",
  );
  const merged = mergeRecommendations(
    [
      {
        id: "c1",
        title: "C",
        channel: "Ch",
        channelId: "u",
        durationSec: 200,
        published: "V",
        score: 98,
        why: "w",
        isCurated: true,
      },
    ],
    [
      {
        id: "c1",
        title: "dup",
        channel: "Ch",
        channelId: "u",
        durationSec: 200,
        published: "",
        score: 70,
        why: "w",
      },
    ],
    6,
  );
  ok(merged.length === 1, "merge dedupes");

  /* ------------------------------------------------------------------ */
  section("Adaptive planner re-ranking on weak topics");
  const rows2 = [
    {
      id: "t1",
      subject: "Physics",
      chapter: "Kinematics",
      topic: "Projectile",
      kind: "learn",
      date: localDayKey(now),
      estMin: 60,
      status: "pending",
    },
    {
      id: "t2",
      subject: "Physics",
      chapter: "Kinematics",
      topic: "Projectile",
      kind: "practice",
      date: localDayKey(now),
      estMin: 45,
      status: "pending",
    },
    {
      id: "t3",
      subject: "Chemistry",
      chapter: "Mole Concept",
      topic: "",
      kind: "learn",
      date: localDayKey(now),
      estMin: 30,
      status: "done",
    },
  ];
  const adapted = adaptTasks(
    rows2,
    [
      {
        subject: "Physics",
        chapter: "Kinematics",
        topic: "Projectile",
        accuracy: 25,
        attemptCount: 4,
        reason: "weak",
      },
    ],
    now,
  );
  ok(adapted.tasks[0].isWeakTarget === true, "adaptive ranks weak first");
  ok(adapted.tasks[0].rank === 1, "adaptive assigns rank 1");

  /* ------------------------------------------------------------------ */
  // clean up
  await rm(dir, { recursive: true, force: true }).catch(() => {});

  console.log("\n============================================================");
  console.log(`Cases exercised: ${stats.cases}`);
  console.log(`Passed: ${passed}  Failed: ${failed}  Throws: ${stats.throws}`);
  if (failures.length) {
    console.error("\nFailed assertions:");
    for (const f of failures.slice(0, 60)) console.error("  - " + f);
    process.exit(1);
  }
  console.log("All FULL-PLATFORM validation checks passed ✅");
}

main().catch((e) => {
  console.error("FATAL: " + (e && e.stack ? e.stack : e));
  process.exit(1);
});
