#!/usr/bin/env node
/**
 * VALIDATE AI PLANNER — full-corpus + adversarial robustness harness.
 *
 * Bundles the *real* planner source (normalize, engine, adapt, readiness,
 * store, video-engine, teachers, syllabus) with Rolldown and runs the actual
 * production functions against:
 *
 *  1. A large generated corpus: every official syllabus topic × subject ×
 *     kind × depth × target × language (+ teacher/institute preferences),
 *     plus every legacy topic. This "training set" exercises the full
 *     decision surface so the planner must never crash or return malformed
 *     recommendations in any real combination.
 *  2. Ranking invariants on fabricated live YouTube candidates.
 *  3. Adversarial / malformed request payloads (null, arrays, objects, huge
 *     strings, NaN, unknown enums, unicode, whitespace-only, stopword topics).
 *  4. Readiness + adaptive-plan invariants on synthetic student stores.
 *
 * Exits non-zero on any failed assertion (CI-friendly). No network is used;
 * the recommendation engine's search function is stubbed.
 */

import { build } from "rolldown";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src");

/* ------------------------------------------------------------------ */
/* Tiny test framework                                                */
/* ------------------------------------------------------------------ */
let passed = 0;
let failed = 0;
const failures = [];
const stats = { scenarios: 0, curatedEmpty: 0, fallbackEmpty: 0, throws: 0 };

function ok(cond, label) {
  if (cond) {
    passed++;
  } else {
    failed++;
    failures.push(label);
    console.error("  ✗ " + label);
  }
}
function section(title) {
  console.log("\n=== " + title + " ===");
}

/* ------------------------------------------------------------------ */
/* Build the bundle                                                    */
/* ------------------------------------------------------------------ */
const entryPath = join(tmpdir(), `ntacbt-planner-entry-${process.pid}.ts`);

// Build a correct entry with explicit paths
function buildEntry() {
  const lines = ["// @generated by scripts/validate-planner.mjs"];
  lines.push(
    `export * as normalize from ${JSON.stringify(join(SRC, "features", "planner", "normalize"))};`,
  );
  lines.push(
    `export * as engine from ${JSON.stringify(join(SRC, "features", "planner", "engine"))};`,
  );
  lines.push(
    `export * as adapt from ${JSON.stringify(join(SRC, "features", "planner", "adapt"))};`,
  );
  lines.push(
    `export * as readiness from ${JSON.stringify(join(SRC, "features", "readiness", "readiness"))};`,
  );
  lines.push(`export * as store from ${JSON.stringify(join(SRC, "lib", "store"))};`);
  lines.push(`export * as video from ${JSON.stringify(join(SRC, "data", "video-engine"))};`);
  lines.push(`export * as teachers from ${JSON.stringify(join(SRC, "data", "teachers"))};`);
  lines.push(`export * as syllabus from ${JSON.stringify(join(SRC, "data", "syllabus"))};`);
  lines.push(
    `export * as catalog from ${JSON.stringify(join(SRC, "features", "studytube", "catalog"))};`,
  );
  return lines.join("\n");
}

let P;
async function buildBundle() {
  await writeFile(entryPath, buildEntry(), "utf8");
  const out = join(tmpdir(), `ntacbt-planner-bundle-${process.pid}.mjs`);
  const res = await build({
    input: entryPath,
    output: { file: out, format: "esm" },
    resolve: { tsconfigFilename: join(ROOT, "tsconfig.json") },
    platform: "node",
  });
  if (!res || !res.output) throw new Error("Rolldown produced no output");
  P = await import(pathToFileURL(out).href);
  return out;
}

/* ------------------------------------------------------------------ */
/* Corpus generation                                                   */
/* ------------------------------------------------------------------ */
function flatSyllabusTopics() {
  const out = [];
  const subjects = P.syllabus.JEE_MAIN_2026_SYLLABUS.subjects || [];
  for (const subj of subjects) {
    for (const ch of subj.chapters || []) {
      const topics = ch.topics && ch.topics.length ? ch.topics.map((t) => t.name) : [ch.name];
      for (const topic of topics) out.push({ topic, subject: ch.subject || subj.name });
    }
  }
  return out;
}

async function main() {
  section("Build planner bundle");
  await buildBundle();
  ok(typeof P.engine.planRecommendations === "function", "engine.planRecommendations exported");
  ok(typeof P.normalize.sanitizePlannerRequest === "function", "normalize exported");
  console.log("  bundle built, exports loaded");

  const { sanitizePlannerRequest, hasPlannerTopic } = P.normalize;
  const {
    planRecommendations,
    rank,
    buildQueries,
    mergeRecommendations,
    parseDuration,
    parseSearchPage,
    resolveCuratedFor,
    REAL_YT_ID,
  } = P.engine;
  const {
    matchCanonicalTopic,
    resolveCuratedVideos,
    generateConsistentCuratedSet,
    CURATED_TOPIC_REGISTRY,
  } = P.video;
  const { offlineCatalog, dreamChannels } = P.catalog;
  const { TEACHERS, INSTITUTES, teachersForTarget, boardCoreTeachersFor, isBoardTarget } =
    P.teachers;
  const { adaptTasks } = P.adapt;
  const { computeReadiness } = P.readiness;
  const { DataStore, localDayKey } = P.store;

  /* ------------------------------------------------------------------ */
  section("Adversarial input sanitization (must never throw / leak)");
  const adversarial = [
    ["null", null],
    ["undefined", undefined],
    ["number", 42],
    ["string", "hello"],
    ["array", [1, 2, 3]],
    ["empty object", {}],
    ["topic object", { topic: { evil: true } }],
    ["topic array", { topic: ["a", "b"] }],
    ["huge topic", { topic: "x".repeat(10000) }],
    ["huge subject", { subject: "y".repeat(10000) }],
    ["whitespace topic", { topic: "   " }],
    ["unicode topic", { topic: "विद्युत आवेश 电荷" }],
    ["nan minutes", { topic: "t", maxMinutes: "not-a-number" }],
    ["inf minutes", { topic: "t", maxMinutes: "Infinity" }],
    ["negative minutes", { topic: "t", maxMinutes: -5000 }],
    ["huge minutes", { topic: "t", maxMinutes: 1e9 }],
    ["unknown kind", { topic: "t", kind: "podcast" }],
    ["unknown target", { topic: "t", target: "neet" }],
    ["teacher object", { topic: "t", teacher: { id: "x" } }],
    ["teacherId precedence", { topic: "t", teacherId: "ex", teacher: "fallback" }],
    ["boolean fields", { topic: "t", language: true, depth: false }],
  ];
  let prevTopic = null;
  for (const [name, input] of adversarial) {
    stats.scenarios++;
    try {
      const r = sanitizePlannerRequest(input);
      ok(typeof r.topic === "string" && r.topic.length <= 120, `${name}: topic bounded string`);
      ok(
        Number.isFinite(r.maxMinutes) && r.maxMinutes >= 10 && r.maxMinutes <= 600,
        `${name}: maxMinutes clamped`,
      );
      ok(
        Number.isFinite(r.minMinutes) && r.minMinutes >= 0 && r.minMinutes <= 300,
        `${name}: minMinutes clamped`,
      );
      ok(["en", "hi", "hinglish"].includes(r.language), `${name}: language in enum`);
      ok(["learn", "practice", "revision", "advanced"].includes(r.kind), `${name}: kind in enum`);
      if (name === "topic object" || name === "topic array") prevTopic = r.topic;
    } catch (e) {
      stats.throws++;
      ok(false, `${name}: threw ${e && e.message}`);
    }
  }
  ok(prevTopic === "", "object/array topic coerced to empty (never [object Object])");

  /* ------------------------------------------------------------------ */
  section("parseDuration edge cases");
  ok(parseDuration("1:02:33") === 3753, "parseDuration h:mm:ss");
  ok(parseDuration("12:34") === 754, "parseDuration mm:ss");
  ok(parseDuration("0:58") === 58, "parseDuration 0:ss");
  ok(parseDuration("") === 0, "parseDuration empty -> 0");
  ok(parseDuration("abc") === 0, "parseDuration garbage -> 0");
  ok(parseDuration("LIVE") === 0, "parseDuration LIVE -> 0");
  ok(parseDuration("9:99") === 0, "parseDuration invalid component -> 0");

  /* ------------------------------------------------------------------ */
  section("parseSearchPage synthetic HTML");
  const renderer1 = {
    videoId: "abc123",
    title: { runs: [{ text: "Kinematics Full Lecture JEE Main" }] },
    ownerText: {
      runs: [
        { text: "Physics Wallah", navigationEndpoint: { browseEndpoint: { browseId: "UCxx" } } },
      ],
    },
    lengthText: { simpleText: "2:30:00" },
    publishedTimeText: { simpleText: "2 years ago" },
  };
  const renderer2 = {
    videoId: "live1",
    title: { runs: [{ text: "Live Class" }] },
    ownerText: { runs: [{ text: "Ch" }] },
    lengthText: { simpleText: "" },
    thumbnailOverlays: [{ thumbnailOverlayTimeStatusRenderer: { style: "LIVE" } }],
  };
  const fakeHtml =
    "var ytInitialData = " +
    JSON.stringify({
      contents: {
        twoColumnSearchResultsRenderer: {
          primaryContents: {
            sectionListRenderer: {
              contents: [
                { itemSectionRenderer: { contents: [{ videoRenderer: renderer1 }] } },
                { itemSectionRenderer: { contents: [{ videoRenderer: renderer2 }] } },
              ],
            },
          },
        },
      },
    }) +
    ";</script>";
  const parsed = parseSearchPage(fakeHtml);
  // parseSearchPage keeps the live entry (marked live), rank() drops it later.
  ok(parsed.length === 2, "parseSearchPage parses valid + live video");
  ok(parsed[0] && parsed[0].durationSec === 9000, "parseSearchPage duration 2:30:00 -> 9000");
  ok(parsed[1] && parsed[1].live === true, "parseSearchPage marks live entry");

  /* ------------------------------------------------------------------ */
  section("Full decision-surface corpus (every topic in the official syllabus)");
  const kinds = ["learn", "practice", "revision", "advanced"];
  const depths = ["oneshot", "lecture", "detailed"];
  const targets = ["jeemain", "jeeadv", "board12", "board11", "cbse27"];
  const languages = ["en", "hi", "hinglish"];
  const syllabus = flatSyllabusTopics();
  ok(syllabus.length > 100, `syllabus corpus has ${syllabus.length} topic/subject pairs`);

  // stub search that returns a couple of plausible candidates for a query
  const stubSearch = async (query) => {
    // derive a topic-ish token from the query to fake real results
    const words = query
      .split(/\s+/)
      .filter((w) => w.length > 2)
      .slice(0, 3)
      .join(" ");
    return [
      {
        id: "v" + Math.abs(hashStr(query)).toString(36),
        title: `${words} Complete Lecture JEE Main | Physics Wallah`,
        channel: "JEE Wallah",
        channelId: "UCxx",
        durationSec: 7200,
        published: "1 year ago",
        live: false,
      },
      {
        id: "v2" + Math.abs(hashStr(query)).toString(36),
        title: `${words} One Shot Revision Mind Map | Unacademy`,
        channel: "Unacademy JEE",
        channelId: "UCyy",
        durationSec: 3600,
        published: "1 month ago",
        live: false,
      },
    ];
  };

  let coverage = 0;
  let noCoverage = [];
  for (const { topic, subject } of syllabus) {
    stats.scenarios++;
    // coverage: every official topic must map to a curated registry set
    const set = matchCanonicalTopic(topic, subject);
    const lessons = resolveCuratedVideos({
      topic,
      subject,
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    if (set && lessons.length) coverage++;
    else noCoverage.push(`${subject}:${topic}`);
  }
  ok(
    coverage > 0,
    `coverage: ${coverage}/${syllabus.length} syllabus topics resolve curated lessons`,
  );
  console.log(
    `  no curated coverage for ${noCoverage.length} topics (fallback search handles these)`,
  );

  /* ------------------------------------------------------------------ */
  section("Full curated registry coverage (every canonical topic)");
  const registryKeys = Object.keys(CURATED_TOPIC_REGISTRY);
  ok(registryKeys.length > 0, `curated registry has ${registryKeys.length} canonical topics`);
  const registryMissing = [];
  for (const key of registryKeys) {
    stats.scenarios++;
    const set = CURATED_TOPIC_REGISTRY[key];
    if (!set || !set.lessons || !set.lessons.length) {
      registryMissing.push(key);
      continue;
    }
    const lessons = resolveCuratedVideos({
      topic: set.canonicalName,
      subject: set.subject,
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    ok(lessons.length > 0, `registry topic resolves lessons: ${key}`);
  }
  ok(
    registryMissing.length === 0,
    `all registry topics have lessons (${registryMissing.length} missing)`,
  );

  /* ------------------------------------------------------------------ */
  section("Seeded fuzz across random topic/subject + all axes");
  // Deterministic LCG so the test is reproducible, but exercises unlikely strings.
  let seed = 1337;
  const rnd = () => {
    seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
    return seed / 2 ** 32;
  };
  const weirdTopics = [
    "Electrostatics",
    "ray optics and optical instruments",
    "differential equations",
    "coordinate geometry 3d",
    "",
    "the and for of",
    "alcohols, phenols & ethers",
    "rotational motion  ",
    "मोल संकल्पना",
    "thermodynamics [with] entropy",
    "electromagnetic induction (EMI)",
    "a",
    "&",
    "kinematics-v2",
  ];
  for (let i = 0; i < 220; i++) {
    stats.scenarios++;
    const topic = weirdTopics[Math.floor(rnd() * weirdTopics.length)];
    const subject = ["Physics", "Chemistry", "Mathematics", "", "English"][Math.floor(rnd() * 5)];
    const kind = kinds[Math.floor(rnd() * kinds.length)];
    const depth = depths[Math.floor(rnd() * depths.length)];
    const target = targets[Math.floor(rnd() * targets.length)];
    const lang = languages[Math.floor(rnd() * languages.length)];
    try {
      const r = sanitizePlannerRequest({ topic, subject, kind, depth, target, language: lang });
      const res = await planRecommendations(r, stubSearch);
      ensureValidPlan(res.items);
    } catch (e) {
      stats.throws++;
      ok(
        false,
        `fuzz #${i} (${subject}/${kind}/${depth}/${target}/${lang}) threw: ${e && e.message}`,
      );
    }
  }
  console.log("  ran 220 seeded adversarial fuzz combos");
  ok(stats.throws === 0, "no throws across fuzz corpus");

  /* ------------------------------------------------------------------ */
  section("Offline catalog + dream channels (always-works fallback)");
  for (const subject of ["Physics", "Chemistry", "Mathematics", "English"]) {
    stats.scenarios++;
    const items = offlineCatalog({
      topic: "Kinematics",
      subject,
      language: "hinglish",
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    ok(Array.isArray(items) && items.length > 0, `offlineCatalog non-empty for ${subject}`);
    ok(
      items.every((it) => it.externalUrl && it.externalUrl.startsWith("https://")),
      `offlineCatalog picks open a real YouTube search (${subject})`,
    );
    ok(
      items.every((it) => it.id && it.title && it.channel),
      `offlineCatalog items well-formed (${subject})`,
    );
    const dreams = dreamChannels({
      topic: "Kinematics",
      subject,
      language: "en",
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    ok(Array.isArray(dreams), `dreamChannels returns array for ${subject}`);
  }

  // exhaustive combos on a representative topic to bound runtime but cover all axes
  let combo = 0;
  for (const subject of ["Physics", "Chemistry", "Mathematics", "English"]) {
    const topic = subject === "English" ? "Reading Comprehension" : "Kinematics";
    for (const kind of kinds) {
      for (const depth of depths) {
        for (const target of targets) {
          for (const lang of languages) {
            stats.scenarios++;
            combo++;
            const raw = { topic, subject, language: lang, kind, depth, target };
            try {
              const r = sanitizePlannerRequest(raw);
              const res = await planRecommendations(r, stubSearch);
              ensureValidPlan(res.items);
              ok(res.items.length <= 6, `combo res items <= 6 (${combo})`);
              ok(
                res.items[0]?.isCurated !== false || res.items.length > 0,
                `combo non-empty (${combo})`,
              );
            } catch (e) {
              stats.throws++;
              ok(
                false,
                `combo ${subject}/${kind}/${depth}/${target}/${lang} threw: ${e && e.message}`,
              );
            }
          }
        }
      }
    }
  }
  console.log(`  ran ${combo} exhaustive kind/depth/target/language combos`);

  /* ------------------------------------------------------------------ */
  section("Teacher / institute preference combinations");
  const teacherIds = TEACHERS.slice(0, 12).map((t) => t.id);
  const instituteIds = INSTITUTES.slice(0, 6).map((i) => i.id);
  for (const subject of ["Physics", "Chemistry", "Mathematics"]) {
    for (const tid of teacherIds) {
      stats.scenarios++;
      const r = sanitizePlannerRequest({
        topic: "Kinematics",
        subject,
        teacher: tid,
        kind: "learn",
      });
      const res = await planRecommendations(r, stubSearch);
      ensureValidPlan(res.items);
    }
    for (const iid of instituteIds) {
      stats.scenarios++;
      const r = sanitizePlannerRequest({
        topic: "Kinematics",
        subject,
        institute: iid,
        kind: "revision",
      });
      const res = await planRecommendations(r, stubSearch);
      ensureValidPlan(res.items);
    }
    // unknown teacher / institute must not throw and should not crash (fallback)
    stats.scenarios++;
    const r = sanitizePlannerRequest({
      topic: "Kinematics",
      subject,
      teacher: "Nobody Sir",
      institute: "NoSuchCoaching",
    });
    const res = await planRecommendations(r, stubSearch);
    ensureValidPlan(res.items);
  }

  /* ------------------------------------------------------------------ */
  section("Ranking invariants on fabricated live candidates");
  const live = [
    {
      id: "r1",
      title: "Kinematics Projectile Complete JEE Main one shot",
      channel: "Physics Wallah",
      channelId: "u1",
      durationSec: 7200,
      published: "2y",
      live: false,
    },
    {
      id: "r2",
      title: "#shorts quick song",
      channel: "Music",
      channelId: "u2",
      durationSec: 30,
      published: "1y",
      live: false,
    },
    {
      id: "r3",
      title: "LIVE now",
      channel: "Live",
      channelId: "u3",
      durationSec: 0,
      published: "",
      live: true,
    },
    {
      id: "r4",
      title: "Kinematics revision one shot",
      channel: "Unacademy",
      channelId: "u4",
      durationSec: 2700,
      published: "1m",
      live: false,
    },
    {
      id: "r5",
      title: "Chemistry mole concept",
      channel: "PW",
      channelId: "u5",
      durationSec: 5400,
      published: "1y",
      live: false,
    },
  ];
  const ranked = rank(live, "Kinematics", "en", "learn", 180, "", "lecture", 0, "jeemain");
  ok(Array.isArray(ranked), "rank returns array");
  ok(ranked.length > 0, "rank returns relevant kinematics items");
  ok(
    ranked.every((i) => i.durationSec >= 65),
    "rank excludes shorts/too-short",
  );
  ok(
    ranked.every((i) => !/shorts|song/i.test(i.title)),
    "rank excludes shorts/song",
  );
  // a topic with no token-bearing live results (stopword topic) returns []
  const rankedEmpty = rank(live, "the and for", "en", "learn", 180);
  ok(Array.isArray(rankedEmpty), "rank on stopword topic returns array (no throw)");

  // PLAN-SYNC (audit 2026-09): a small planned slot must not pick an
  // hours-long video — the systematic "video length ≠ dashboard minutes"
  // mismatch on every task.
  const fitLive = [
    {
      id: "f1",
      title: "Kinematics one shot complete",
      channel: "PW",
      channelId: "u1",
      durationSec: 2700,
      published: "1y",
      live: false,
    },
    {
      id: "f2",
      title: "Kinematics complete marathon lecture",
      channel: "PW",
      channelId: "u1",
      durationSec: 14400,
      published: "1y",
      live: false,
    },
  ];
  const fitRanked = rank(fitLive, "Kinematics", "en", "learn", 45, "", "oneshot", 18, "jeemain");
  ok(
    fitRanked.some((i) => i.id === "f1"),
    "small planned slot keeps the fitting video",
  );
  ok(
    !fitRanked.some((i) => i.id === "f2"),
    "small planned slot rejects the 4-hour video",
  );

  /* ------------------------------------------------------------------ */
  section("Merge: curated-first, no duplicates, bounded");
  const curated = [
    {
      id: "c1",
      title: "C1",
      channel: "Ch",
      channelId: "u",
      durationSec: 100,
      published: "Verified",
      score: 98,
      why: "w",
      verified: true,
      isCurated: true,
    },
    {
      id: "c1",
      title: "C1 dup",
      channel: "Ch",
      channelId: "u",
      durationSec: 100,
      published: "Verified",
      score: 98,
      why: "w",
      verified: true,
      isCurated: true,
    },
  ];
  const merged = mergeRecommendations(
    curated,
    [
      {
        id: "l1",
        title: "L1",
        channel: "Ch",
        channelId: "u",
        durationSec: 100,
        published: "",
        score: 90,
        why: "w",
      },
      {
        id: "c1",
        title: "dup",
        channel: "Ch",
        channelId: "u",
        durationSec: 100,
        published: "",
        score: 70,
        why: "w",
      },
    ],
    6,
  );
  ok(merged.length === 2, "merge dedupes + bounded (got " + merged.length + ")");
  ok(merged[0].isCurated === true, "merge puts curated first");

  /* ------------------------------------------------------------------ */
  section("buildQueries safety");
  const qs = buildQueries(
    "Kinematics",
    "Physics",
    "hinglish",
    "practice",
    "",
    "lecture",
    "jeemain",
    "",
    "",
  );
  ok(Array.isArray(qs) && qs.length > 0 && qs.length <= 4, "buildQueries bounded");
  ok(
    qs.every((q) => typeof q === "string" && q.length > 0),
    "buildQueries non-empty strings",
  );

  /* ------------------------------------------------------------------ */
  section("Readiness + adaptive planner (synthetic student stores)");
  const now = Date.now();
  const attempts = [
    {
      id: "a1",
      testId: "t1",
      submittedAt: now,
      result: { all: { correct: 2, wrong: 8, skipped: 0, marks: 0, neg: 0, time: 10, total: 10 } },
      responses: {},
    },
  ];
  const tests = [
    {
      id: "t1",
      name: "Diag",
      createdAt: now,
      duration: 60,
      questions: Array.from({ length: 10 }, (_, i) => ({
        id: `q${i}`,
        subject: i < 5 ? "Physics" : "Chemistry",
        chapter: i < 5 ? "Kinematics" : "Mole Concept",
        type: "mcq",
        text: "q",
        options: [],
        answer: String.fromCharCode(65 + (i % 4)),
      })),
    },
  ];
  // weak: 2 correct in 8 kinematics attempts -> meets weak-threshold (>=2 attempts)
  const store = new DataStore({
    attempts,
    tests,
    settings: {},
    dailyQuestions: {},
    reviewSchedule: {},
    qtags: {},
    aiPlanner: {
      profile: {
        target: "jeemain",
        language: "en",
        depth: "lecture",
        speed: 1,
        dailyMin: 120,
        weekdayMin: 90,
        startDate: "2026-09-03",
        days: 90,
      },
      tasks: [
        {
          id: "pk",
          subject: "Physics",
          chapter: "Kinematics",
          topic: "Projectile",
          kind: "learn",
          date: localDayKey(now),
          estMin: 60,
          status: "pending",
          why: "prio",
        },
        {
          id: "cb",
          subject: "Chemistry",
          chapter: "Mole Concept",
          topic: "",
          kind: "practice",
          date: localDayKey(now),
          estMin: 45,
          status: "pending",
        },
      ],
    },
    plannerDone: { pk: true },
    plannerEdits: {},
  });
  const rs = computeReadiness(store);
  ok(
    typeof rs.accuracy === "number" && rs.accuracy >= 0 && rs.accuracy <= 100,
    "readiness accuracy in range",
  );
  ok(Array.isArray(rs.weakTopics), "readiness weakTopics array");
  ok(typeof rs.syllabusCompletionPct === "number", "readiness syllabusCompletionPct number");
  // plannerDone overlay: completedToday / planner must reflect pk done
  ok(
    store.completedToday(now).some((t) => t.id === "pk"),
    "completedToday reflects plannerDone overlay",
  );
  ok(
    store.planner.tasks.find((t) => t.id === "pk").status === "done",
    "planner getter overlays done",
  );

  const adapted = adaptTasks(
    [
      {
        id: "d1",
        subject: "Physics",
        chapter: "Kinematics",
        topic: "Projectile",
        kind: "learn",
        date: localDayKey(now),
        estMin: 60,
        status: "pending",
      },
      {
        id: "d2",
        subject: "Physics",
        chapter: "Kinematics",
        topic: "Projectile",
        kind: "learn",
        date: localDayKey(now),
        estMin: 45,
        status: "done",
      },
      {
        id: "d3",
        subject: "Chemistry",
        chapter: "Mole Concept",
        topic: "",
        kind: "practice",
        date: localDayKey(now),
        estMin: 30,
        status: "pending",
      },
    ],
    [
      {
        subject: "Physics",
        chapter: "Kinematics",
        topic: "Projectile",
        accuracy: 25,
        attemptCount: 4,
        reason: "weak",
      },
    ],
    now,
  );
  ok(adapted.tasks.length === 3, "adapt returns all rows");
  ok(adapted.weakUsed.length === 1, "adapt detects weak match");
  ok(adapted.tasks[0].isWeakTarget === true, "adapt ranks weak target first");
  ok(adapted.tasks[0].rank === 1, "adapt assigns ranks 1..n");

  /* ------------------------------------------------------------------ */
  section("CBSE Class 12 board target: board-core teachers ONLY (no JEE/NEET)");
  const JEE_LEAK =
    /jee main|jee advanced|\biit\b|\bneet\b|manzil|lakshya|prayas|pankaj sir|mohit tyagi|physics galaxy/i;
  for (const subject of ["Physics", "Chemistry", "Mathematics"]) {
    stats.scenarios++;
    const t = "board12";
    const boardTeachers = teachersForTarget(t, subject);
    ok(boardTeachers.length > 0, `board target has board-core teachers for ${subject}`);
    ok(
      boardTeachers.every((x) => x.boardCore === true),
      `board target exposes ONLY board-core educators (${subject})`,
    );
    ok(
      boardTeachers.every(
        (x) => !x.examTarget.includes("jeemain") && !x.examTarget.includes("jeeadv"),
      ),
      `board-core educators never tagged JEE/NEET (${subject})`,
    );

    // dream channels are board-core only
    const dc = dreamChannels({
      topic: "Physics",
      subject,
      language: "hinglish",
      kind: "learn",
      depth: "lecture",
      target: t,
    });
    ok(dc.length > 0, `dreamChannels non-empty for board ${subject}`);
    ok(
      dc.every((c) => c.boardCore === true),
      `dreamChannels for board are board-core (${subject})`,
    );

    // offline catalog board picks: never JEE language, durations in board band
    const cat = offlineCatalog({
      topic: "Physics",
      subject,
      language: "hinglish",
      kind: "learn",
      depth: "detailed",
      target: t,
    });
    ok(cat.length > 0, `offlineCatalog non-empty for board ${subject}`);
    ok(
      cat.every((v) => v.externalUrl && !JEE_LEAK.test(v.externalUrl)),
      `board offline picks avoid JEE/NEET keywords (${subject})`,
    );
    ok(
      cat.every((v) => v.durationSec >= 45 * 60 && v.durationSec <= 240 * 60),
      `board offline durations are board-range (${subject})`,
    );

    // end-to-end curated board set (production board path — network independent)
    const rr = sanitizePlannerRequest({
      topic: "Electrostatics",
      subject,
      kind: "learn",
      depth: "detailed",
      target: t,
      language: "hinglish",
    });
    const curatedBoard = resolveCuratedFor(rr);
    ok(curatedBoard.length > 0, `board curated set has items (${subject})`);
    ok(
      curatedBoard.every((it) => !JEE_LEAK.test((it.title || "") + " " + (it.channel || ""))),
      `board curated items have no JEE/NEET leak (${subject})`,
    );
    ok(
      curatedBoard.every((it) => it.durationSec >= 20 * 60),
      `board curated items are not tiny clips (${subject})`,
    );
    ok(
      curatedBoard.every(
        (it) =>
          (P.engine.REAL_YT_ID.test(it.id) && it.verified) || // real verified board video
          (it.externalUrl && !it.verified), // honest search-pick fallback
      ),
      `board curated items are either verified videos or honest search-picks (${subject})`,
    );
    // the "detailed" board curated pick sits in the board-detailed band and is board-labelled
    const detailed = curatedBoard.find((it) => it.durationSec >= 7200 && it.durationSec <= 12600);
    ok(detailed !== undefined, `board detailed pick exists (${subject})`);
    ok(
      /class 12|cbse|board/i.test(detailed.title || ""),
      `board detailed pick is board-labelled (${subject})`,
    );
    ok(
      !/jeemain|jee advanced|iit|neet/i.test(detailed.why || ""),
      `board detailed why is board-not-JEE (${subject})`,
    );
  }
  // JEE target must NOT be restricted to board-core (JEE faculties still present)
  const jeeTeachers = teachersForTarget("jeemain", "Physics");
  ok(
    jeeTeachers.some((x) => x.boardCore !== true),
    "JEE target still exposes JEE faculties (not over-restricted)",
  );

  /* ------------------------------------------------------------------ */
  section("Curated board registry ids are real YouTube video ids (verified)");
  const BOARD_VIDEO_REGISTRY = P.video.BOARD_VIDEO_REGISTRY || [];
  ok(
    Array.isArray(BOARD_VIDEO_REGISTRY) && BOARD_VIDEO_REGISTRY.length > 0,
    "board registry present",
  );
  for (const set of BOARD_VIDEO_REGISTRY) {
    stats.scenarios++;
    ok(
      set && Array.isArray(set.lessons) && set.lessons.length > 0,
      `board set has lessons: ${set.canonicalName}`,
    );
    for (const l of set.lessons || []) {
      ok(P.engine.REAL_YT_ID.test(l.id), `board lesson id is a real YT id: ${l.title}`);
      // Only oEmbed-verified entries may carry the embed-allowed flag.
      ok(
        l.verifiedReal === true,
        `board lesson is oEmbed-verified (verifiedReal): ${l.title}`,
      );
      ok(l.teacher && l.channel, `board lesson has teacher+channel: ${l.title}`);
      ok(l.kind && l.depth, `board lesson has kind/depth: ${l.title}`);
      ok(l.target === "board12" || l.target === "cbse27", `board lesson targets board: ${l.title}`);
      ok(
        Number.isFinite(l.durationSec) && l.durationSec >= 20 * 60,
        `board lesson duration sane: ${l.title}`,
      );
    }
  }
  console.log(
    `  validated ${BOARD_VIDEO_REGISTRY.length} board topics / ${BOARD_VIDEO_REGISTRY.reduce((n, s) => n + (s.lessons?.length || 0), 0)} verified lessons`,
  );

  /* ------------------------------------------------------------------ */
  section("generateConsistentCuratedSet never returns empty for any subject");
  for (const subject of ["Physics", "Chemistry", "Mathematics", "English"]) {
    const sets = generateConsistentCuratedSet({
      topic: "Anything",
      subject,
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    ok(Array.isArray(sets) && sets.length > 0, `consistent set non-empty for ${subject}`);
    // Synthetic fallback ids (ce-*) must NEVER masquerade as a real verified video.
    ok(
      sets.every((s) => !REAL_YT_ID.test(s.id)),
      `consistent set uses non-video fallback ids (not verified) for ${subject}`,
    );
    ok(
      sets.every((s) => s.playlistUrl && s.playlistUrl.startsWith("https://")),
      `consistent set links to a real search (${subject})`,
    );
  }

  /* ------------------------------------------------------------------ */
  section("Curated honesty contract: unverified lessons are search-picks, never fake embeds");
  // Audit 2026-09: the JEE registry's 11-char ids are placeholders that do not
  // exist on YouTube (oEmbed: Not Found). An 11-char SHAPE is not proof of a
  // video, so the engine embeds a lesson ONLY when verifiedReal === true.
  // Everything else must resolve as an honest search-pick: synthetic non-video
  // id, https externalUrl, verified falsy, duration labelled estimated.
  let registryVi = 0;
  for (const key of Object.keys(CURATED_TOPIC_REGISTRY)) {
    stats.scenarios++;
    const set = CURATED_TOPIC_REGISTRY[key];
    if (!set || !set.lessons || !set.lessons.length) continue;
    const req = sanitizePlannerRequest({
      topic: set.canonicalName,
      subject: set.subject,
      kind: "learn",
      depth: "lecture",
      target: "jeemain",
    });
    const lessons = resolveCuratedFor(req);
    ok(lessons.length > 0, `resolves for ${key}`);
    for (const it of lessons) {
      const raw = set.lessons.find(
        (l) => l.title === it.title || it.title.startsWith(l.title.slice(0, 24)),
      );
      if (raw && raw.verifiedReal === true) {
        ok(
          REAL_YT_ID.test(it.id) && it.verified === true && !it.externalUrl,
          `verified lesson embeds as a real video: ${it.title.slice(0, 40)}`,
        );
      } else {
        ok(!REAL_YT_ID.test(it.id), `unverified pick id is NOT video-shaped: ${key}`);
        ok(
          it.externalUrl && it.externalUrl.startsWith("https://www.youtube.com/results?"),
          `unverified pick opens a targeted search: ${key}`,
        );
        ok(!it.verified, `unverified pick is NOT marked verified: ${key}`);
        ok(
          it.durationEstimated === true,
          `unverified pick duration labelled estimated: ${key}`,
        );
      }
      ensureValidPlan([it]);
    }
    // Determinism: identical requests produce identical pick ids (cache/dedupe/keys).
    const again = resolveCuratedFor(req);
    ok(
      again.map((x) => x.id).join(",") === lessons.map((x) => x.id).join(","),
      `search-pick ids are deterministic: ${key}`,
    );
    registryVi++;
  }
  console.log(`  honesty contract enforced across ${registryVi} registry topics`);

  /* ------------------------------------------------------------------ */
  // Cleanup
  try {
    await rm(entryPath, { force: true });
  } catch {}

  console.log("\n============================================================");
  console.log(`Scenarios exercised: ${stats.scenarios}`);
  console.log(`Passed: ${passed}  Failed: ${failed}`);
  if (failures.length) {
    console.error("\nFailed assertions:");
    for (const f of failures) console.error("  - " + f);
    process.exit(1);
  }
  console.log("All AI-planner validation checks passed ✅");
}

function ensureValidPlan(items) {
  ok(Array.isArray(items), "plan returns array");
  ok(items.length <= 6, "plan bounded to 6");
  const ids = new Set();
  for (const it of items) {
    ok(it && typeof it.id === "string" && it.id.length > 0, "item has non-empty id");
    ok(typeof it.title === "string" && it.title.length > 0, "item has title");
    ok(typeof it.channel === "string" && it.channel.length > 0, "item has channel");
    ok(Number.isFinite(it.durationSec) && it.durationSec >= 0, "item has sane duration");
    ok(typeof it.score === "number" && Number.isFinite(it.score), "item score is finite number");
    ok(typeof it.why === "string" && it.why.length > 0, "item has explainable why");
    ok(!ids.has(it.id), "item id unique");
    // A "verified" curated pick must reference a real YouTube video; synthetic
    // fallback ids (ce-*) are search-picks and must NOT be labelled verified.
    if (it.verified) {
      ok(P.engine.REAL_YT_ID.test(it.id), `verified item has a real YT id: ${it.id}`);
    } else if (it.isCurated && it.id.startsWith("ce-")) {
      ok(!it.verified, `synthetic ${it.id} is NOT marked verified`);
    }
    ids.add(it.id);
  }
}

function hashStr(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (Math.imul(31, h) + s.charCodeAt(i)) | 0;
  return h;
}

main().catch((e) => {
  console.error("FATAL: " + (e && e.stack ? e.stack : e));
  process.exit(1);
});
