/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAiChatRouteImport } from './routes/api/public/ai-chat'
import { Route as ApiPublicCloudConfigRouteImport } from './routes/api/public/cloud-config'
import { Route as ApiPublicLiveClassesRouteImport } from './routes/api/public/live-classes'
import { Route as ApiPublicPdfReformatRouteImport } from './routes/api/public/pdf-reformat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiChatRoute = ApiPublicAiChatRouteImport.update({
  id: '/api/public/ai-chat',
  path: '/api/public/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudConfigRoute = ApiPublicCloudConfigRouteImport.update({
  id: '/api/public/cloud-config',
  path: '/api/public/cloud-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveClassesRoute = ApiPublicLiveClassesRouteImport.update({
  id: '/api/public/live-classes',
  path: '/api/public/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPdfReformatRoute = ApiPublicPdfReformatRouteImport.update({
  id: '/api/public/pdf-reformat',
  path: '/api/public/pdf-reformat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/cloud-config': typeof ApiPublicCloudConfigRoute
  '/api/public/live-classes': typeof ApiPublicLiveClassesRoute
  '/api/public/pdf-reformat': typeof ApiPublicPdfReformatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/cloud-config': typeof ApiPublicCloudConfigRoute
  '/api/public/live-classes': typeof ApiPublicLiveClassesRoute
  '/api/public/pdf-reformat': typeof ApiPublicPdfReformatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/cloud-config': typeof ApiPublicCloudConfigRoute
  '/api/public/live-classes': typeof ApiPublicLiveClassesRoute
  '/api/public/pdf-reformat': typeof ApiPublicPdfReformatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/ai-chat'
    | '/api/public/cloud-config'
    | '/api/public/live-classes'
    | '/api/public/pdf-reformat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/ai-chat'
    | '/api/public/cloud-config'
    | '/api/public/live-classes'
    | '/api/public/pdf-reformat'
  id:
    | '__root__'
    | '/'
    | '/api/public/ai-chat'
    | '/api/public/cloud-config'
    | '/api/public/live-classes'
    | '/api/public/pdf-reformat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAiChatRoute: typeof ApiPublicAiChatRoute
  ApiPublicCloudConfigRoute: typeof ApiPublicCloudConfigRoute
  ApiPublicLiveClassesRoute: typeof ApiPublicLiveClassesRoute
  ApiPublicPdfReformatRoute: typeof ApiPublicPdfReformatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-chat': {
      id: '/api/public/ai-chat'
      path: '/api/public/ai-chat'
      fullPath: '/api/public/ai-chat'
      preLoaderRoute: typeof ApiPublicAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud-config': {
      id: '/api/public/cloud-config'
      path: '/api/public/cloud-config'
      fullPath: '/api/public/cloud-config'
      preLoaderRoute: typeof ApiPublicCloudConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-classes': {
      id: '/api/public/live-classes'
      path: '/api/public/live-classes'
      fullPath: '/api/public/live-classes'
      preLoaderRoute: typeof ApiPublicLiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pdf-reformat': {
      id: '/api/public/pdf-reformat'
      path: '/api/public/pdf-reformat'
      fullPath: '/api/public/pdf-reformat'
      preLoaderRoute: typeof ApiPublicPdfReformatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAiChatRoute: ApiPublicAiChatRoute,
  ApiPublicCloudConfigRoute: ApiPublicCloudConfigRoute,
  ApiPublicLiveClassesRoute: ApiPublicLiveClassesRoute,
  ApiPublicPdfReformatRoute: ApiPublicPdfReformatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
