/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CbtRouteImport } from './routes/cbt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLayoutRouteImport } from './routes/app._layout'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppFocusRouteImport } from './routes/app.focus'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPyqRouteImport } from './routes/app.pyq'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppSaarthiRouteImport } from './routes/app.saarthi'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppStudytubeRouteImport } from './routes/app.studytube'
import { Route as AppTestsRouteImport } from './routes/app.tests'
import { Route as ApiPublicAiChatRouteImport } from './routes/api/public/ai-chat'
import { Route as ApiPublicCloudConfigRouteImport } from './routes/api/public/cloud-config'
import { Route as ApiPublicLiveClassesRouteImport } from './routes/api/public/live-classes'
import { Route as ApiPublicPdfReformatRouteImport } from './routes/api/public/pdf-reformat'
import { Route as ApiPublicPyqPapersRouteImport } from './routes/api/public/pyq-papers'
import { Route as ApiPublicStudyPlannerRouteImport } from './routes/api/public/study-planner'
import { Route as AppAuthLoginRouteImport } from './routes/app.auth.login'
import { Route as AppAuthRegisterRouteImport } from './routes/app.auth.register'
import { Route as AppStudytubeVideoRouteImport } from './routes/app.studytube.$video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CbtRoute = CbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/app/focus',
  path: '/app/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/app/map',
  path: '/app/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/app/memory',
  path: '/app/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/app/planner',
  path: '/app/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPyqRoute = AppPyqRouteImport.update({
  id: '/app/pyq',
  path: '/app/pyq',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/app/report',
  path: '/app/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSaarthiRoute = AppSaarthiRouteImport.update({
  id: '/app/saarthi',
  path: '/app/saarthi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudytubeRoute = AppStudytubeRouteImport.update({
  id: '/app/studytube',
  path: '/app/studytube',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/app/tests',
  path: '/app/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiChatRoute = ApiPublicAiChatRouteImport.update({
  id: '/api/public/ai-chat',
  path: '/api/public/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudConfigRoute = ApiPublicCloudConfigRouteImport.update({
  id: '/api/public/cloud-config',
  path: '/api/public/cloud-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveClassesRoute = ApiPublicLiveClassesRouteImport.update({
  id: '/api/public/live-classes',
  path: '/api/public/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPdfReformatRoute = ApiPublicPdfReformatRouteImport.update({
  id: '/api/public/pdf-reformat',
  path: '/api/public/pdf-reformat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPyqPapersRoute = ApiPublicPyqPapersRouteImport.update({
  id: '/api/public/pyq-papers',
  path: '/api/public/pyq-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStudyPlannerRoute = ApiPublicStudyPlannerRouteImport.update({
  id: '/api/public/study-planner',
  path: '/api/public/study-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/app/auth/login',
  path: '/app/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRegisterRoute = AppAuthRegisterRouteImport.update({
  id: '/app/auth/register',
  path: '/app/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudytubeVideoRoute = AppStudytubeVideoRouteImport.update({
  id: '/$video',
  path: '/$video',
  getParentRoute: () => AppStudytubeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cbt': typeof CbtRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AppLayoutRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/map': typeof AppMapRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pyq': typeof AppPyqRoute
  '/app/report': typeof AppReportRoute
  '/app/saarthi': typeof AppSaarthiRoute
  '/app/search': typeof AppSearchRoute
  '/app/studytube': typeof AppStudytubeRouteWithChildren
  '/app/tests': typeof AppTestsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/cloud-config': typeof ApiPublicCloudConfigRoute
  '/api/public/live-classes': typeof ApiPublicLiveClassesRoute
  '/api/public/pdf-reformat': typeof ApiPublicPdfReformatRoute
  '/api/public/pyq-papers': typeof ApiPublicPyqPapersRoute
  '/api/public/study-planner': typeof ApiPublicStudyPlannerRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/app/auth/register': typeof AppAuthRegisterRoute
  '/app/studytube/$video': typeof AppStudytubeVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cbt': typeof CbtRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AppIndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/map': typeof AppMapRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pyq': typeof AppPyqRoute
  '/app/report': typeof AppReportRoute
  '/app/saarthi': typeof AppSaarthiRoute
  '/app/search': typeof AppSearchRoute
  '/app/studytube': typeof AppStudytubeRouteWithChildren
  '/app/tests': typeof AppTestsRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/cloud-config': typeof ApiPublicCloudConfigRoute
  '/api/public/live-classes': typeof ApiPublicLiveClassesRoute
  '/api/public/pdf-reformat': typeof ApiPublicPdfReformatRoute
  '/api/public/pyq-papers': typeof ApiPublicPyqPapersRoute
  '/api/public/study-planner': typeof ApiPublicStudyPlannerRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/app/auth/register': typeof AppAuthRegisterRoute
  '/app/studytube/$video': typeof AppStudytubeVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cbt': typeof CbtRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/_layout': typeof AppLayoutRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/map': typeof AppMapRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pyq': typeof AppPyqRoute
  '/app/report': typeof AppReportRoute
  '/app/saarthi': typeof AppSaarthiRoute
  '/app/search': typeof AppSearchRoute
  '/app/studytube': typeof AppStudytubeRouteWithChildren
  '/app/tests': typeof AppTestsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/cloud-config': typeof ApiPublicCloudConfigRoute
  '/api/public/live-classes': typeof ApiPublicLiveClassesRoute
  '/api/public/pdf-reformat': typeof ApiPublicPdfReformatRoute
  '/api/public/pyq-papers': typeof ApiPublicPyqPapersRoute
  '/api/public/study-planner': typeof ApiPublicStudyPlannerRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/app/auth/register': typeof AppAuthRegisterRoute
  '/app/studytube/$video': typeof AppStudytubeVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cbt'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/app/analytics'
    | '/app/focus'
    | '/app/map'
    | '/app/memory'
    | '/app/planner'
    | '/app/profile'
    | '/app/pyq'
    | '/app/report'
    | '/app/saarthi'
    | '/app/search'
    | '/app/studytube'
    | '/app/tests'
    | '/app/'
    | '/api/public/ai-chat'
    | '/api/public/cloud-config'
    | '/api/public/live-classes'
    | '/api/public/pdf-reformat'
    | '/api/public/pyq-papers'
    | '/api/public/study-planner'
    | '/app/auth/login'
    | '/app/auth/register'
    | '/app/studytube/$video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cbt'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/app/analytics'
    | '/app/focus'
    | '/app/map'
    | '/app/memory'
    | '/app/planner'
    | '/app/profile'
    | '/app/pyq'
    | '/app/report'
    | '/app/saarthi'
    | '/app/search'
    | '/app/studytube'
    | '/app/tests'
    | '/api/public/ai-chat'
    | '/api/public/cloud-config'
    | '/api/public/live-classes'
    | '/api/public/pdf-reformat'
    | '/api/public/pyq-papers'
    | '/api/public/study-planner'
    | '/app/auth/login'
    | '/app/auth/register'
    | '/app/studytube/$video'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cbt'
    | '/privacy'
    | '/terms'
    | '/app/_layout'
    | '/app/analytics'
    | '/app/focus'
    | '/app/map'
    | '/app/memory'
    | '/app/planner'
    | '/app/profile'
    | '/app/pyq'
    | '/app/report'
    | '/app/saarthi'
    | '/app/search'
    | '/app/studytube'
    | '/app/tests'
    | '/app/'
    | '/api/public/ai-chat'
    | '/api/public/cloud-config'
    | '/api/public/live-classes'
    | '/api/public/pdf-reformat'
    | '/api/public/pyq-papers'
    | '/api/public/study-planner'
    | '/app/auth/login'
    | '/app/auth/register'
    | '/app/studytube/$video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CbtRoute: typeof CbtRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AppLayoutRoute: typeof AppLayoutRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppFocusRoute: typeof AppFocusRoute
  AppMapRoute: typeof AppMapRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPyqRoute: typeof AppPyqRoute
  AppReportRoute: typeof AppReportRoute
  AppSaarthiRoute: typeof AppSaarthiRoute
  AppSearchRoute: typeof AppSearchRoute
  AppStudytubeRoute: typeof AppStudytubeRouteWithChildren
  AppTestsRoute: typeof AppTestsRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiPublicAiChatRoute: typeof ApiPublicAiChatRoute
  ApiPublicCloudConfigRoute: typeof ApiPublicCloudConfigRoute
  ApiPublicLiveClassesRoute: typeof ApiPublicLiveClassesRoute
  ApiPublicPdfReformatRoute: typeof ApiPublicPdfReformatRoute
  ApiPublicPyqPapersRoute: typeof ApiPublicPyqPapersRoute
  ApiPublicStudyPlannerRoute: typeof ApiPublicStudyPlannerRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
  AppAuthRegisterRoute: typeof AppAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt': {
      id: '/cbt'
      path: '/cbt'
      fullPath: '/cbt'
      preLoaderRoute: typeof CbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/focus': {
      id: '/app/focus'
      path: '/app/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/map': {
      id: '/app/map'
      path: '/app/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/app/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/app/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pyq': {
      id: '/app/pyq'
      path: '/app/pyq'
      fullPath: '/app/pyq'
      preLoaderRoute: typeof AppPyqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/report': {
      id: '/app/report'
      path: '/app/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/saarthi': {
      id: '/app/saarthi'
      path: '/app/saarthi'
      fullPath: '/app/saarthi'
      preLoaderRoute: typeof AppSaarthiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search': {
      id: '/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studytube': {
      id: '/app/studytube'
      path: '/app/studytube'
      fullPath: '/app/studytube'
      preLoaderRoute: typeof AppStudytubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tests': {
      id: '/app/tests'
      path: '/app/tests'
      fullPath: '/app/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-chat': {
      id: '/api/public/ai-chat'
      path: '/api/public/ai-chat'
      fullPath: '/api/public/ai-chat'
      preLoaderRoute: typeof ApiPublicAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud-config': {
      id: '/api/public/cloud-config'
      path: '/api/public/cloud-config'
      fullPath: '/api/public/cloud-config'
      preLoaderRoute: typeof ApiPublicCloudConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-classes': {
      id: '/api/public/live-classes'
      path: '/api/public/live-classes'
      fullPath: '/api/public/live-classes'
      preLoaderRoute: typeof ApiPublicLiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pdf-reformat': {
      id: '/api/public/pdf-reformat'
      path: '/api/public/pdf-reformat'
      fullPath: '/api/public/pdf-reformat'
      preLoaderRoute: typeof ApiPublicPdfReformatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pyq-papers': {
      id: '/api/public/pyq-papers'
      path: '/api/public/pyq-papers'
      fullPath: '/api/public/pyq-papers'
      preLoaderRoute: typeof ApiPublicPyqPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/study-planner': {
      id: '/api/public/study-planner'
      path: '/api/public/study-planner'
      fullPath: '/api/public/study-planner'
      preLoaderRoute: typeof ApiPublicStudyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth/login': {
      id: '/app/auth/login'
      path: '/app/auth/login'
      fullPath: '/app/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth/register': {
      id: '/app/auth/register'
      path: '/app/auth/register'
      fullPath: '/app/auth/register'
      preLoaderRoute: typeof AppAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studytube/$video': {
      id: '/app/studytube/$video'
      path: '/$video'
      fullPath: '/app/studytube/$video'
      preLoaderRoute: typeof AppStudytubeVideoRouteImport
      parentRoute: typeof AppStudytubeRoute
    }
  }
}

interface AppStudytubeRouteChildren {
  AppStudytubeVideoRoute: typeof AppStudytubeVideoRoute
}

const AppStudytubeRouteChildren: AppStudytubeRouteChildren = {
  AppStudytubeVideoRoute: AppStudytubeVideoRoute,
}

const AppStudytubeRouteWithChildren = AppStudytubeRoute._addFileChildren(
  AppStudytubeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CbtRoute: CbtRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AppLayoutRoute: AppLayoutRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppFocusRoute: AppFocusRoute,
  AppMapRoute: AppMapRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppPyqRoute: AppPyqRoute,
  AppReportRoute: AppReportRoute,
  AppSaarthiRoute: AppSaarthiRoute,
  AppSearchRoute: AppSearchRoute,
  AppStudytubeRoute: AppStudytubeRouteWithChildren,
  AppTestsRoute: AppTestsRoute,
  AppIndexRoute: AppIndexRoute,
  ApiPublicAiChatRoute: ApiPublicAiChatRoute,
  ApiPublicCloudConfigRoute: ApiPublicCloudConfigRoute,
  ApiPublicLiveClassesRoute: ApiPublicLiveClassesRoute,
  ApiPublicPdfReformatRoute: ApiPublicPdfReformatRoute,
  ApiPublicPyqPapersRoute: ApiPublicPyqPapersRoute,
  ApiPublicStudyPlannerRoute: ApiPublicStudyPlannerRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
  AppAuthRegisterRoute: AppAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
